"""
Phase 5 — Evaluation & PR Creation Agent.

Assigns a confidence score to the patch, runs the generated tests,
and creates a GitHub Pull Request draft.
Scoring: +0.4 (addresses bug), +0.3 (minimal change), +0.2 (test quality), +0.1 (diff format).
Updated: 2026-04-01
"""
import logging
import subprocess

from app.state import FixoraState
from app.tools.llm_client import get_llm_client
from app.tools.github_client import create_pull_request

logger = logging.getLogger("fixora.agents.evaluator")

EVAL_PROMPT = """
You are a strict code reviewer. Score the following patch on a scale from 0.0 to 1.0.

Consider:
- Does it directly address the reported bug? (+0.4)
- Is the change minimal and safe (no regressions)? (+0.3)
- Is the generated test meaningful? (+0.2)
- Is the diff syntactically well-formed? (+0.1)

## Issue Summary
{summary}

## Patch Diff
{patch_diff}

## Generated Test
{test_code}

Respond with ONLY a JSON object: {{"score": <0.0-1.0>, "reasoning": "<one sentence>"}}
"""


async def _score_patch(state: FixoraState) -> tuple[float, str]:
    """Ask the LLM to self-evaluate the generated patch."""
    llm = get_llm_client()
    classified = state.get("classified_issue", {})
    prompt = EVAL_PROMPT.format(
        summary=classified.get("summary", ""),
        patch_diff=state.get("patch_diff", "")[:3000],
        test_code=state.get("test_code", "")[:1500],
    )
    try:
        import json
        resp = await llm.ainvoke(prompt)
        content = (resp.content if hasattr(resp, "content") else str(resp)).strip()
        content = content.strip("```json").strip("```").strip()
        data = json.loads(content)
        return float(data.get("score", 0.5)), data.get("reasoning", "")
    except Exception:
        return 0.5, "Auto-scored (LLM eval failed)"


def _run_tests(test_file_path: str, repo_path: str) -> bool:
    """Run the generated pytest file; return True if all tests pass."""
    if not test_file_path or not repo_path:
        return False
    try:
        result = subprocess.run(
            ["pytest", test_file_path, "-v", "--tb=short", "--timeout=30"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=60,
        )
        passed = result.returncode == 0
        logger.info(f"[Evaluator] Test result: {'PASS' if passed else 'FAIL'}\n{result.stdout[-1000:]}")
        return passed
    except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
        logger.warning(f"[Evaluator] Could not run tests: {exc}")
        return False


def _build_pr_body(state: FixoraState, confidence: float, reasoning: str, test_passed: bool) -> str:
    classified = state.get("classified_issue", {})
    snippets = state.get("relevant_snippets", [])
    file_list = "\n".join(f"- `{s['file_path']}`" for s in snippets) or "_Unknown_"

    test_status = "✅ All tests passed" if test_passed else "⚠️ Tests skipped or failed (manual review needed)"

    return f"""## 🤖 Fixora Automated Fix

Closes #{state.get('issue_number', '?')}

### 🐛 Issue Summary
**{state.get('issue_title', '')}**

{classified.get('summary', '')}

- **Type:** {classified.get('type', 'bug')}
- **Severity:** {classified.get('severity', 'medium')}
- **Affected Component:** `{classified.get('component', 'unknown')}`

### 🔍 Suspected Bug Locations
{file_list}

### 🔧 Patch Description
This fix was automatically generated by Fixora's patch agent. The unified diff is included in this PR's file changes.

### 🧪 Test Results
{test_status}

### 📊 Confidence Score
**{confidence:.0%}** — {reasoning}

---
*This PR was auto-generated by [Fixora](https://github.com/fixora-ai). Please review carefully before merging.*
"""


async def evaluator_node(state: FixoraState) -> FixoraState:
    """LangGraph node: scores the patch, runs tests, creates the GitHub PR."""
    patch_diff = state.get("patch_diff", "")
    repo_url = state.get("repo_url", "")

    if not patch_diff:
        return {**state, "error": "evaluator: no patch_diff to evaluate", "current_phase": "evaluate"}

    logger.info("[Evaluator] Scoring patch...")
    confidence, reasoning = await _score_patch(state)
    logger.info(f"[Evaluator] Confidence: {confidence:.2f} — {reasoning}")

    test_passed = _run_tests(
        state.get("test_file_path", ""),
        state.get("repo_local_path", ""),
    )

    pr_body = _build_pr_body(state, confidence, reasoning, test_passed)
    pr_title = f"[Fixora] Fix: {state.get('issue_title', 'Automated patch')} (Issue #{state.get('issue_number')})"
    branch_name = f"fixora/issue-{state.get('issue_number', 'auto')}"

    try:
        pr_url, pr_number = create_pull_request(
            repo_url=repo_url,
            branch_name=branch_name,
            title=pr_title,
            body=pr_body,
            draft=True,
        )
        logger.info(f"[Evaluator] PR created: {pr_url} (#{pr_number})")
        return {
            **state,
            "confidence_score": confidence,
            "test_passed": test_passed,
            "pr_url": pr_url,
            "pr_number": pr_number,
            "current_phase": "done",
        }
    except Exception as exc:
        logger.warning(f"[Evaluator] PR creation skipped/failed (Dry Run mode active?): {exc}")
        return {
            **state,
            "confidence_score": confidence,
            "test_passed": test_passed,
            "error": f"evaluator: PR creation skipped ({exc})",
            "current_phase": "done",
        }
